HaterClient/HaterClient/ViewModels/MatchViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HaterClient.Models.Enums;

namespace HaterClient.ViewModels
{
    public class MatchViewModel
    {
        public int MatchId { get; set; }
        public string Name { get; set; }
        public Gender Gender { get; set; }
        public int Age { get; set; }
        public string Description { get; set; }
        public List<VoteViewModel> Choices { get; set; }
        public bool UserAccept { get; set; }
        public bool MatchAccept { get; set; }
    }

    public class MatchUserViewModel
    {
        public int MatchId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public bool UserAccept { get; set; }
        public bool MatchAccept { get; set; }
    }
}

HaterClient/HaterClient/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using HaterClient.Services;
using HaterClient.ViewModels;

namespace HaterClient.Controllers
{
    public class MatchController : Controller
    {
        private readonly MatchService _matchService = new MatchService();
        
        public async Task<ActionResult> Index()
        {
            GetToken();
            if (ViewBag.Token == null || string.IsNullOrEmpty(ViewBag.Token))
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new MatchViewModel();

            try
            {
                vm = await _matchService.GetMatch(ViewBag.Token);
            }
            catch (Exception e)
            {
                // ignored
            }

            return View(vm);
        }

        public async Task<ActionResult> Pending()
        {
            GetToken();
            if (ViewBag.Token == null || String.IsNullOrEmpty(ViewBag.Token))
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new List<MatchUserViewModel>();

            try
            {
                vm = await _matchService.GetPending(ViewBag.Token);
            }
            catch (Exception e)
            {
                // ignored
            }

            return View(vm);
        }

        public string GetToken()
        {
            HttpCookie token = this.Request.Cookies["token"];
            if (token != null)
            {
                ViewBag.Token = token.Value;
                return token.Value;
            }
            return null;
        }
    }
}

HaterClient/HaterClient/Views/Match/Index.cshtml
@model HaterClient.ViewModels.MatchViewModel
@{
    ViewBag.Title = "Match me";
}

@if (Model.MatchId > 0)
{

    <h1>You got matched with @Model.Name</h1>
    <hr />
    <p>
        @Model.Gender<br />
        @Model.Age<br />
        @Model.Description
    </p>
    <hr />
    using (Html.BeginForm("Index", "Match"))
    {
         @Html.AntiForgeryToken()

    }
    <ul>
        
    </ul>
}
else
{
    <h1>Match me</h1>

    <hr />
    <h2 class="text-danger">No more matches...</h2>
}

HaterClient/HaterClient/Views/Match/Pending.cshtml
@model List<HaterClient.ViewModels.MatchUserViewModel>
@{
    ViewBag.Title = "Pending matches";
}

<h1>Pending matches</h1>
<hr />

@if (Model.Count > 0)
{
    <ul>
        
    </ul>
}
else
{
    <h2 class="text-danger">No more pending matches...</h2>
}