HaterClient/HaterClient/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.WebParts;
using HaterClient.Models;
using HaterClient.Services;
using HaterClient.ViewModels;

namespace HaterClient.Controllers
{
    public class TopicController : Controller
    {
        private readonly TopicService _topicService;
        private readonly VoteService _voteService;
        // GET: Topic
        public TopicController()
        {
            _topicService = new TopicService();
            _voteService = new VoteService();
        }

        public string GetToken()
        {
            HttpCookie token = this.Request.Cookies["token"];
            if (token != null)
            {
                ViewBag.Token = token.Value;
                return token.Value;
            }
            return null;
        }

        public async Task<ActionResult> Index()
        {
            GetToken();
            if (ViewBag.Token == null || String.IsNullOrEmpty(ViewBag.Token))
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new AnswersTopicVm
            {
                Choices = new List<UserTopicChoice>()
            };

            try
            {
                vm.Choices = await _topicService.GetAll(ViewBag.Token);
            }
            catch (Exception e)
            {
                // ignored
            }
            //var topics = await _topicService.GetAllTopics(ViewBag.Token);
            return View(vm);
        }
       
        public ActionResult Create()
        {
            GetToken();
            if (ViewBag.Token == null || String.IsNullOrEmpty(ViewBag.Token))
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new CreateTopicViewModel();
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateTopicViewModel vm)
        {
            GetToken();
            if (ViewBag.Token == null || String.IsNullOrEmpty(ViewBag.Token))
            {
                return RedirectToAction("Index", "Home");
            }

            if (!string.IsNullOrEmpty(vm.Topic))
            {
                var topic = new Topic()
                {
                    Description = vm.Topic,
                    CreatedAt = DateTime.Now,
                    Approved = true,
                };

                try
                {
                    await _topicService.Create(topic, GetToken());
                    vm = new CreateTopicViewModel()
                    {
                        Topic = "",
                        Message = "Your topic has been submitted!",
                        Success = true
                    };
                }
                catch (Exception e)
                {
                    vm.Message = "Topic has allready been submitted.";
                    vm.Success = false;
                }
            }
            else
            {
                vm.Message = "Please enter a topic";
                vm.Success = false;
            }

            return View(vm);
        }

        public async Task<ActionResult> Vote()
        {
            GetToken();
            if (ViewBag.Token == null || String.IsNullOrEmpty(ViewBag.Token))
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new VoteViewModel();
            var topic = new VoteTopicGetViewModel();

            try
            {
                topic = await _voteService.Get(ViewBag.Token);
            }
            catch (Exception e)
            {
                // ignored
            }

            if (topic.TopicId > 0)
            {
                vm.TopicId = topic.TopicId;
                vm.Description = topic.Description;
            }
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Vote(VoteViewModel vm)
        {
            GetToken();
            if (ViewBag.Token == null || String.IsNullOrEmpty(ViewBag.Token))
            {
                return RedirectToAction("Index", "Home");
            }

            if (vm.TopicId > 0)
            {
                var choice = new VoteTopicPostViewModel()
                {
                    TopicId = vm.TopicId,
                    Choice = vm.Choice
                };

                try
                {
                    await _voteService.Vote(choice, GetToken());
                }
                catch (Exception e)
                {
                    // ignored
                }
            }

            return RedirectToAction("Vote");
        }
    }
}

HaterClient/HaterClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hater | @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hater", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
           
            @if (ViewBag.Token != null && ViewBag.Token.Length > 0)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Create a topic", "Create", "Topic")</li>
                        <li>@Html.ActionLink("Vote on a topic", "Vote", "Topic")</li>
                        <li>@Html.ActionLink("My answers", "Index", "Topic")</li>
                        <li>@Html.ActionLink("Match", "Index", "Match")</li>
                        <li>@Html.ActionLink("Pending matches", "Pending", "Match")</li>
                        <li>@Html.ActionLink("Chat", "Index", "Chat")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("My profile", "Profile", "Home")</li>
                        <li><button class="btn btn-link navbar-btn navbar-link">Log out</button></li>
                    </ul>
                </div>
            }
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hater</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app")

    @RenderSection("scripts", required: false)
</body>
</html>